# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: QualitySofts
email: sarker.shantonu@gmail.com
description: We Ensure Quality of Software
baseurl: "/startbootstrap-freelancer-jekyll" # the subpath of your site, e.g. /blog
url: "https://qualitysofts.github.io/" # the base hostname & protocol for your site
url-pretty: "qualitysofts.github.io"
# Social media profiles - feel free to add more here
twitter_username:
github_username:  qualitysofts
facebook_username:
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
address_street: Ghoramara
address_city: Rajshahi
address_state: Rajshahi
address_zip: 6100

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-github-metadata
  - jekyll-youtube